server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TESTING?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 1225
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show_sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true